POST http://localhost:3001/subscore HTTP/1.1
content-type: application/json

{
    "username": "ZAC",
    "newscore": {{$randomInt 1 9999}}
}

###
# Username Truncation
POST http://localhost:3001/subscore HTTP/1.1
content-type: application/json

{
    "username": "ZACLONGNAMETOOLONGINFACT",
    "newscore": 10
}

###
# Get Contiguous, lastID is the target ID so choose carefully
GET http://localhost:3001/contiguous?limit=9&lastID=10 HTTP/1.1
content-type: application/json

 
###
# Default GET top 100 highscores
GET http://localhost:3001/scores HTTP/1.1
content-type: application/json 


###
# Limit top scores request to x highest scores
GET http://localhost:3001/scores?limit=2 HTTP/1.1
content-type: application/json 

###
# Randomize for stress test
POST http://localhost:3001/admin/randomizeDB HTTP/1.1
content-type: application/json

{
    "amount": 10000,
    "key": "put key here, this puts tons of random data in the db, do not use live"
}


### REST Client for Visual Studio Code by Huachao Mao is recommended for easy use of these test routes